channel_priority: strict
channels:
  - conda-forge
  - defaults
  - bioconda
  - pypi
dependencies:
  - snakemake==8.1.2
  - pulp==2.7.0
  - python==3.11.0
  - numpy>=1.23.5
  - pip>=20.3.3
  - astropy==5.1
  - pandas >=1.1.3
  - scipy >= 1.4.1
  - pip:

      - matplotlib==3.4.3
      - showyourwork==0.4.3
